# Purpose -----------------------------------------------------------------
# Quantify the annual taxonomic resolution of selected ICCAT Task I nominal
# catch records associated with Resolution 19-01 species.

required_packages <- c(
  "dplyr",
  "ggplot2",
  "here",
  "readr",
  "scales",
  "tidyr"
)

missing_packages <- required_packages[
  !vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)
]

if (length(missing_packages) > 0) {
  stop(
    "Missing packages: ",
    paste(missing_packages, collapse = ", "),
    ". Install them once, then record the environment with renv::snapshot()."
  )
}

suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(here)
  library(readr)
  library(scales)
  library(tidyr)
})

# Paths -------------------------------------------------------------------
processed_file <- here("data", "processed", "task1_selected_res19_01.rds")
table_dir <- here("outputs", "01_data", "tables")
figure_dir <- here("outputs", "01_data", "figures")

dir.create(table_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(figure_dir, recursive = TRUE, showWarnings = FALSE)

if (!file.exists(processed_file)) {
  stop(
    "Processed Task I data not found. Run ",
    "R/01_data/01_import_validate_task1.R first."
  )
}

task1_selected <- readRDS(processed_file)

year_min <- 1950L
year_max <- 2023L

reporting_levels <- c(
  "Species",
  "Genus aggregate",
  "Family aggregate"
)

resolution_colours <- c(
  "Species" = "#0072B2",
  "Genus aggregate" = "#E69F00",
  "Family aggregate" = "#999999"
)

cmm_years <- tibble::tribble(
  ~Year, ~CMM,
  2005L, "Rec. 04-10",
  2008L, "Rec. 07-06"
)

# Only families with at least one aggregate record can change among all
# three reporting levels. Other Resolution 19-01 families remain in the
# taxon-presence audit generated by script 01.
families_with_aggregate_records <- task1_selected %>%
  filter(Reporting_level != "Species") %>%
  distinct(Family) %>%
  pull(Family)

resolution_annual <- task1_selected %>%
  filter(Family %in% families_with_aggregate_records) %>%
  mutate(
    Reporting_level = factor(
      Reporting_level,
      levels = reporting_levels
    )
  ) %>%
  group_by(Year, Family, Reporting_level) %>%
  summarise(
    Catch_t = sum(Catch_t),
    Number_records = n(),
    Positive_records = sum(Positive_record),
    Number_flags_any_record = n_distinct(Flag),
    Number_flags_positive = n_distinct(Flag[Positive_record]),
    .groups = "drop"
  ) %>%
  complete(
    Year = year_min:year_max,
    Family = families_with_aggregate_records,
    Reporting_level = factor(reporting_levels, levels = reporting_levels),
    fill = list(
      Catch_t = 0,
      Number_records = 0,
      Positive_records = 0,
      Number_flags_any_record = 0,
      Number_flags_positive = 0
    )
  ) %>%
  group_by(Year, Family) %>%
  mutate(
    Annual_family_catch_t = sum(Catch_t),
    Catch_share = if_else(
      Annual_family_catch_t > 0,
      Catch_t / Annual_family_catch_t,
      NA_real_
    )
  ) %>%
  ungroup() %>%
  arrange(Family, Year, Reporting_level)

# Sensitivity analysis: blue shark strongly dominates Carcharhinidae catch
# weight and can mask changes in unresolved reporting.
resolution_sensitivity <- bind_rows(
  task1_selected %>% mutate(Scenario = "All selected records"),
  task1_selected %>%
    filter(Scientific_name != "Prionace glauca") %>%
    mutate(Scenario = "Excluding blue shark")
) %>%
  filter(Family %in% families_with_aggregate_records) %>%
  group_by(Scenario, Year, Family, Reporting_level) %>%
  summarise(Catch_t = sum(Catch_t), .groups = "drop") %>%
  complete(
    Scenario,
    Year = year_min:year_max,
    Family = families_with_aggregate_records,
    Reporting_level = reporting_levels,
    fill = list(Catch_t = 0)
  ) %>%
  group_by(Scenario, Year, Family) %>%
  mutate(
    Total_t = sum(Catch_t),
    Catch_share = if_else(Total_t > 0, Catch_t / Total_t, NA_real_)
  ) %>%
  ungroup()

# Figures -----------------------------------------------------------------
p_resolution_volume <- ggplot(
  resolution_annual,
  aes(x = Year, y = Catch_t, fill = Reporting_level)
) +
  geom_col(width = 1, colour = NA) +
  geom_vline(
    data = cmm_years,
    aes(xintercept = Year),
    inherit.aes = FALSE,
    linetype = "dashed",
    linewidth = 0.4,
    colour = "black"
  ) +
  facet_wrap(~Family, ncol = 2, scales = "free_y") +
  scale_fill_manual(values = resolution_colours, drop = FALSE) +
  scale_x_continuous(
    breaks = seq(1950, 2020, 10),
    limits = c(year_min, year_max),
    expand = expansion(mult = c(0.005, 0.01))
  ) +
  scale_y_continuous(
    labels = label_number(big.mark = ","),
    expand = expansion(mult = c(0, 0.05))
  ) +
  labs(
    title = "Taxonomic resolution of ICCAT Task I nominal catches",
    subtitle = paste(
      "Annual recorded weight at species, genus, or family level;",
      "reported and estimated records included"
    ),
    x = NULL,
    y = "Nominal catch (t)",
    fill = "Reporting level",
    caption = paste(
      "Dashed lines indicate the first full reporting years associated with",
      "Rec. 04-10 (2005) and Rec. 07-06 (2008)."
    )
  ) +
  theme_classic(base_size = 11) +
  theme(
    legend.position = "bottom",
    strip.background = element_blank(),
    strip.text = element_text(face = "italic"),
    plot.title = element_text(face = "bold"),
    plot.caption = element_text(hjust = 0, size = 8.5)
  )

p_resolution_share <- ggplot(
  resolution_annual,
  aes(x = Year, y = Catch_share, fill = Reporting_level)
) +
  geom_col(width = 1, colour = NA) +
  geom_vline(
    data = cmm_years,
    aes(xintercept = Year),
    inherit.aes = FALSE,
    linetype = "dashed",
    linewidth = 0.4,
    colour = "black"
  ) +
  facet_wrap(~Family, ncol = 2) +
  scale_fill_manual(values = resolution_colours, drop = FALSE) +
  scale_x_continuous(
    breaks = seq(1950, 2020, 10),
    limits = c(year_min, year_max),
    expand = expansion(mult = c(0.005, 0.01))
  ) +
  scale_y_continuous(
    limits = c(0, 1),
    breaks = seq(0, 1, 0.25),
    labels = label_percent(accuracy = 1),
    expand = c(0, 0)
  ) +
  labs(
    title = "Proportional taxonomic resolution of ICCAT Task I nominal catches",
    subtitle = paste(
      "Annual share of recorded weight at each reporting level;",
      "years without positive recorded weight are left blank"
    ),
    x = "Year",
    y = "Proportion of nominal catch",
    fill = "Reporting level",
    caption = paste(
      "Reported and estimated records included. Aggregate records can include",
      "species outside Resolution 19-01 and must be interpreted accordingly."
    )
  ) +
  theme_classic(base_size = 11) +
  theme(
    legend.position = "bottom",
    strip.background = element_blank(),
    strip.text = element_text(face = "italic"),
    plot.title = element_text(face = "bold"),
    plot.caption = element_text(hjust = 0, size = 8.5)
  )

# Save outputs ------------------------------------------------------------
write_csv(
  resolution_annual,
  file.path(table_dir, "taxonomic_resolution_by_family_year.csv"),
  na = ""
)

write_csv(
  resolution_sensitivity,
  file.path(table_dir, "taxonomic_resolution_blue_shark_sensitivity.csv"),
  na = ""
)

ggsave(
  filename = file.path(figure_dir, "taxonomic_resolution_volume.png"),
  plot = p_resolution_volume,
  width = 10,
  height = 8,
  dpi = 320,
  bg = "white"
)

ggsave(
  filename = file.path(figure_dir, "taxonomic_resolution_share.png"),
  plot = p_resolution_share,
  width = 10,
  height = 8,
  dpi = 320,
  bg = "white"
)

message("Taxonomic-resolution tables and figures created successfully.")
print(p_resolution_volume)
print(p_resolution_share)
